# Generated by Django 4.2.3 on 2023-10-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read_app', '0022_remove_archivedstudent_previous_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField()),
                ('section_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.IntegerField(unique=True)),
                ('student_lrn', models.FloatField(null=True, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('grade_level', models.IntegerField()),
                ('class_section', models.CharField(max_length=80)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('has_ongoing_assessment', models.BooleanField(default=False)),
                ('overall_rating', models.CharField(default=0, max_length=100)),
                ('words_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mean_read_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mean_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assessments_done', models.IntegerField(default=0)),
                ('fourth_grade_passage', models.IntegerField(default=0)),
                ('fifth_grade_passage', models.IntegerField(default=0)),
                ('sixth_grade_passage', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('student_id', models.IntegerField()),
                ('student_lrn', models.FloatField(null=True, unique=True)),
                ('grade_level', models.IntegerField()),
                ('class_section', models.CharField(max_length=80)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_archived', models.DateField(auto_now_add=True)),
                ('previous_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
