# Generated by Django 4.2.3 on 2023-10-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_teacher_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='has_ongoing_assessment',
            new_name='is_screened',
        ),
    ]
