# Generated by Django 4.2.3 on 2023-11-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_student_school_id_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='words_per_minute',
        ),
    ]
