# Generated by Django 4.2.3 on 2023-10-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='screening',
            field=models.BooleanField(default=False),
        ),
    ]
