# Generated by Django 4.2.3 on 2023-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_school_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
