# Generated by Django 4.2.3 on 2023-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_student_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='overall_rating',
            field=models.CharField(choices=[('Independent', 'Independent'), ('Instructional', 'Instructional'), ('Frustration', 'Frustration'), ('Not yet screened', 'Not yet screened')], default='Not yet screened', max_length=64),
        ),
    ]
