# Generated by Django 4.2.3 on 2023-10-19 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('read_app', '0020_remove_assessmentsessionpassage_assessment_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('Screening', 'Screening'), ('Normal', 'Normal')], max_length=10)),
                ('grade_level', models.IntegerField()),
                ('total_score', models.IntegerField(null=True)),
                ('total_reading_time', models.PositiveIntegerField(null=True)),
                ('total_answering_time', models.PositiveIntegerField(null=True)),
                ('assigned_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningTestPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField()),
                ('passages', models.ManyToManyField(to='read_app.passage')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSessionPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentsession')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passage')),
            ],
        ),
    ]
