# Generated by Django 4.2.3 on 2023-11-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='extra_reading_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='words_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
