# Generated by Django 4.2.3 on 2023-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentsession_extra_reading_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsessionpassage',
            name='words_per_minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
