# Generated by Django 4.2.3 on 2023-10-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_studentanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentsession'),
            preserve_default=False,
        ),
    ]
