# Generated by Django 4.2.3 on 2023-10-22 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0005_alter_assessmentsession_assessment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='assessment_type',
            field=models.CharField(choices=[('Screening', 'Screening'), ('Graded', 'Graded')], max_length=16),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentsessionpassage',
            name='assessment_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_passage', to='assessment.assessmentsession'),
        ),
        migrations.AlterField(
            model_name='assessmentsessionpassage',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
