# Generated by Django 4.2.3 on 2023-10-23 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_has_ongoing_assessment_student_is_screened'),
        ('assessment', '0007_alter_assessmentsession_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningtestpreset',
            name='passages',
        ),
        migrations.AddField(
            model_name='screeningtestpreset',
            name='name',
            field=models.CharField(default='Screening', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
