# Generated by Django 4.2.3 on 2023-10-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_remove_screeningtestpreset_passages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScreeningTestPreset',
            new_name='AssessmentPreset',
        ),
    ]
