# Generated by Django 4.2.3 on 2023-10-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_rename_screeningtestpreset_assessmentpreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentPreset',
        ),
    ]
