# Generated by Django 4.2.3 on 2023-10-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_studentanswer_answer_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='answer_content',
            new_name='answer',
        ),
    ]
