# Generated by Django 4.2.3 on 2023-10-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_assessmentpreset_passage_preset'),
        ('assessment', '0012_rename_answer_content_studentanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='passage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materials.passage'),
            preserve_default=False,
        ),
    ]
