# Generated by Django 4.2.3 on 2023-10-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_studentanswer_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
