# Generated by Django 4.2.3 on 2023-11-02 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_screening'),
        ('assessment', '0015_alter_studentanswer_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_session', to='students.student'),
        ),
        migrations.CreateModel(
            name='ScreeningAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_passage', models.IntegerField(default=1)),
                ('assessment_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_assessment', to='assessment.assessmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='GradedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graded_assessment', to='assessment.assessmentsession')),
            ],
        ),
    ]
