# Generated by Django 4.2.3 on 2023-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_assessmentsession_student_screeningassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningassessment',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
