# Generated by Django 4.2.3 on 2023-11-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_screeningassessment_number_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningassessment',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
