# Generated by Django 4.2.3 on 2023-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_alter_assessmentsessionpassage_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsessionpassage',
            name='answering_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsessionpassage',
            name='reading_time',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
