# Generated by Django 4.2.3 on 2023-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_assessmentsessionpassage_answering_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsessionpassage',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsessionpassage',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
