# Generated by Django 4.2.3 on 2023-11-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_assessmentsessionpassage_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningassessment',
            name='correct_critical',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='correct_inferential',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='correct_literal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='total_critical',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='total_inferential',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='total_literal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
