# Generated by Django 4.2.3 on 2023-11-20 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField()),
                ('assessment_type', models.CharField(choices=[('Screening', 'Screening'), ('Graded', 'Graded')], max_length=16)),
                ('language', models.CharField(choices=[('English', 'English'), ('Filipino', 'Filipino')])),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Filipino', 'Filipino'), ('English', 'English')])),
                ('set', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], null=True)),
                ('passage_title', models.CharField(max_length=150)),
                ('passage_content', models.CharField(max_length=5000)),
                ('grade_level', models.IntegerField()),
                ('passage_length', models.IntegerField()),
                ('number_of_questions', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.assessmentpreset')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, choices=[('Literal', 'Literal'), ('Inferential', 'Inferential'), ('Critical', 'Critical')], max_length=64, null=True)),
                ('question_content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.passage')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_content', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.question')),
            ],
        ),
    ]
