# Generated by Django 4.2.3 on 2023-10-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='number_of_questions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
