# Generated by Django 4.2.3 on 2023-10-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_passage_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='number_of_questions',
            field=models.IntegerField(null=True),
        ),
    ]
