# Generated by Django 4.2.3 on 2023-10-23 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_passage_number_of_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField()),
                ('assessment_type', models.CharField(choices=[('Screening', 'Screening'), ('Graded', 'Graded')], max_length=16)),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.assessmentpreset'),
        ),
    ]
