# Generated by Django 4.2.3 on 2023-11-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_assessmentpreset_passage_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Literal', 'Literal'), ('Inferential', 'Inferential'), ('Critical', 'Critical')], default='Literal', max_length=64),
            preserve_default=False,
        ),
    ]
