# Generated by Django 4.2.3 on 2023-11-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Literal', 'Literal'), ('Inferential', 'Inferential'), ('Critical', 'Critical')], max_length=64, null=True),
        ),
    ]
