# Generated by Django 4.2.3 on 2023-07-15 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_title', models.CharField(max_length=150)),
                ('passage_content', models.CharField(max_length=5000)),
                ('passage_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(max_length=500)),
                ('question_type', models.CharField(max_length=50)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passage')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('grade_level', models.IntegerField()),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_content', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passagequestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.CharField(max_length=100)),
                ('words_per_minute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mean_read_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mean_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assessments_done', models.IntegerField()),
                ('fourth_grade_passage', models.IntegerField()),
                ('fifth_grade_passage', models.IntegerField()),
                ('sixth_grade_passage', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passagequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.teacher'),
        ),
        migrations.CreateModel(
            name='OpenEnded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passagequestion')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_label', models.CharField(max_length=10)),
                ('choice_content', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passagequestion')),
            ],
        ),
        migrations.CreateModel(
            name='FillBlanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passagequestion')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_passage', models.IntegerField()),
                ('second_passage', models.IntegerField()),
                ('third_passage', models.IntegerField()),
                ('fourth_passage', models.IntegerField()),
                ('time', models.TimeField()),
                ('score', models.IntegerField()),
                ('date_started', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.student')),
            ],
        ),
    ]
