# Generated by Django 4.2.3 on 2023-11-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField()),
                ('grade_name', models.CharField()),
            ],
        ),
    ]
