# Generated by Django 4.2.3 on 2023-11-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grade_level',
            field=models.IntegerField(choices=[], default=4),
            preserve_default=False,
        ),
    ]
