# Generated by Django 4.2.3 on 2023-10-05 00:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0003_teacher_teacher_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('total_reading_time', models.PositiveIntegerField()),
                ('total_answering_time', models.PositiveIntegerField()),
                ('grade_level', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fillblanks',
            name='question',
        ),
        migrations.RemoveField(
            model_name='openended',
            name='question',
        ),
        migrations.RemoveField(
            model_name='truefalse',
            name='question',
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='passage_grade',
            new_name='grade_level',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='choice_label',
        ),
        migrations.RemoveField(
            model_name='passagequestion',
            name='question_type',
        ),
        migrations.AddField(
            model_name='passage',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 10, 5)),
        ),
        migrations.AddField(
            model_name='passage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date(2023, 10, 5)),
        ),
        migrations.AddField(
            model_name='passagequestion',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 10, 5)),
        ),
        migrations.AlterField(
            model_name='archivedstudent',
            name='class_section',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='AssessmentInfo',
        ),
        migrations.DeleteModel(
            name='FillBlanks',
        ),
        migrations.DeleteModel(
            name='OpenEnded',
        ),
        migrations.DeleteModel(
            name='TrueFalse',
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passage'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
