# Generated by Django 4.2.3 on 2023-10-01 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0003_classsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_section',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='ArchivedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('grade_level', models.IntegerField()),
                ('class_section', models.CharField(default='undefined', max_length=80)),
                ('date_archived', models.DateField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
