# Generated by Django 4.2.3 on 2023-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0003_alter_student_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.IntegerField(),
        ),
    ]
