# Generated by Django 4.2.3 on 2023-10-05 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0004_assessmentsession_remove_fillblanks_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='passage',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.RenameModel(
            old_name='MultipleChoice',
            new_name='Choice',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.passage')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.question'),
        ),
        migrations.DeleteModel(
            name='PassageQuestion',
        ),
    ]
