# Generated by Django 4.2.3 on 2023-11-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0004_classsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.CharField(choices=[], default='Rizal'),
            preserve_default=False,
        ),
    ]
