# Generated by Django 4.2.3 on 2023-10-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0004_student_is_archived_alter_student_class_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedstudent',
            name='student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
