# Generated by Django 4.2.3 on 2023-10-12 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0006_alter_choice_is_correct_alter_passage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_lrn',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
