# Generated by Django 4.2.3 on 2023-10-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0006_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
