# Generated by Django 4.2.3 on 2023-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0007_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.PositiveBigIntegerField(),
        ),
    ]
