# Generated by Django 4.2.3 on 2023-10-15 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0008_alter_student_student_lrn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedstudent',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='previous_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivedstudent',
            name='student_lrn',
            field=models.FloatField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='read_app.student'),
        ),
    ]
