# Generated by Django 4.2.3 on 2023-11-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0008_alter_school_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_code',
            field=models.CharField(),
        ),
    ]
