# Generated by Django 4.2.3 on 2023-10-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0009_remove_archivedstudent_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessments_done',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fifth_grade_passage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fourth_grade_passage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mean_read_time',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mean_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='overall_rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sixth_grade_passage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='words_per_minute',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_school_admin',
            field=models.BooleanField(default=False, verbose_name='School Admin status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Teacher status'),
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
