# Generated by Django 4.2.3 on 2023-10-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0010_student_assessments_done_student_fifth_grade_passage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assessments_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='fifth_grade_passage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='fourth_grade_passage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='mean_read_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='mean_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='overall_rating',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='sixth_grade_passage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='words_per_minute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
