# Generated by Django 4.2.3 on 2023-11-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0011_school_district_school_division_school_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='section',
        ),
    ]
