# Generated by Django 4.2.3 on 2023-10-18 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0012_remove_assessmentsession_passage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='assigned_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='total_answering_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='total_reading_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
    ]
