# Generated by Django 4.2.3 on 2023-11-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0012_remove_teacher_grade_level_remove_teacher_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grade_level',
            field=models.IntegerField(choices=[], default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.CharField(choices=[], default='Rizal'),
            preserve_default=False,
        ),
    ]
