# Generated by Django 4.2.3 on 2023-10-18 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0013_assessmentsession_assigned_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='archivedstudent',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='assigned_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
