# Generated by Django 4.2.3 on 2023-11-23 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0014_alter_teacher_grade_level_alter_teacher_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='school_admin', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
