# Generated by Django 4.2.3 on 2023-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0016_assessmentsession_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
