# Generated by Django 4.2.3 on 2023-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0017_assessmentsession_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningTestPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField()),
                ('passages', models.ManyToManyField(to='read_app.passage')),
            ],
        ),
    ]
