# Generated by Django 4.2.3 on 2023-10-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0019_passage_passage_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsessionpassage',
            name='assessment_session',
        ),
        migrations.RemoveField(
            model_name='assessmentsessionpassage',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='screeningtestpreset',
            name='passages',
        ),
        migrations.DeleteModel(
            name='AssessmentSession',
        ),
        migrations.DeleteModel(
            name='AssessmentSessionPassage',
        ),
        migrations.DeleteModel(
            name='ScreeningTestPreset',
        ),
    ]
