# Generated by Django 4.2.3 on 2023-10-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessmentsessionpassage_passage_and_more'),
        ('read_app', '0020_remove_assessmentsessionpassage_assessment_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
