# Generated by Django 4.2.3 on 2023-10-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0021_remove_question_passage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedstudent',
            name='previous_teacher',
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArchivedStudent',
        ),
    ]
