# Generated by Django 4.2.3 on 2023-10-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0022_remove_archivedstudent_previous_teacher_and_more'),
        ('assessment', '0003_alter_studentanswer_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
